export const runs = [
  { id: "run-01", task_name: "Support Ticket Classifier", task_type: "classification", mode: "dataset", base_prompt: "Classify the following support ticket...", scorer: "accuracy", max_iterations: 8, early_stop_threshold: 0.92, variants_per_iter: 5, status: "complete", best_score: 0.94, baseline_score: 0.71, best_prompt: "You are a support classifier...", iterations_run: 5, token_count: 1420, latency_ms: 320, failure_reason: null, created_at: "2026-04-25T10:00:00Z", completed_at: "2026-04-25T10:08:00Z" },
  { id: "run-02", task_name: "Legal Summarizer", task_type: "summarization", mode: "nodataset", base_prompt: "Summarize this contract clause...", scorer: "llm_judge", max_iterations: 10, early_stop_threshold: 0.85, variants_per_iter: 4, status: "running", best_score: 0.78, baseline_score: 0.62, best_prompt: null, iterations_run: 3, token_count: 2100, latency_ms: 450, failure_reason: null, created_at: "2026-04-26T09:15:00Z", completed_at: null },
  { id: "run-03", task_name: "Receipt Data Extractor", task_type: "extraction", mode: "dataset", base_prompt: "Extract date, amount, vendor...", scorer: "accuracy", max_iterations: 8, early_stop_threshold: 0.9, variants_per_iter: 5, status: "complete", best_score: 0.89, baseline_score: 0.65, best_prompt: "Extract structured JSON...", iterations_run: 4, token_count: 980, latency_ms: 280, failure_reason: null, created_at: "2026-04-26T14:20:00Z", completed_at: "2026-04-26T14:29:00Z" },
  { id: "run-04", task_name: "Product Review Judge", task_type: "judge", mode: "nodataset", base_prompt: "Judge if this review is genuine...", scorer: "llm_judge", max_iterations: 6, early_stop_threshold: 0.88, variants_per_iter: 3, status: "queued", best_score: null, baseline_score: null, best_prompt: null, iterations_run: 0, token_count: 0, latency_ms: 0, failure_reason: null, created_at: "2026-04-27T08:00:00Z", completed_at: null },
  { id: "run-05", task_name: "Blog Post Generator", task_type: "generation", mode: "nodataset", base_prompt: "Write a 500-word blog post about...", scorer: "llm_judge", max_iterations: 12, early_stop_threshold: 0.9, variants_per_iter: 6, status: "failed", best_score: 0.41, baseline_score: 0.55, best_prompt: null, iterations_run: 1, token_count: 1800, latency_ms: 620, failure_reason: "LLM API rate limit exceeded", created_at: "2026-04-27T11:30:00Z", completed_at: "2026-04-27T11:31:00Z" },
  { id: "run-06", task_name: "Email Triage Assistant", task_type: "classification", mode: "dataset", base_prompt: "Prioritize incoming emails...", scorer: "accuracy", max_iterations: 8, early_stop_threshold: 0.93, variants_per_iter: 5, status: "running", best_score: 0.82, baseline_score: 0.68, best_prompt: null, iterations_run: 2, token_count: 1100, latency_ms: 310, failure_reason: null, created_at: "2026-04-28T07:45:00Z", completed_at: null }
];

export const variants = [
  { id: "var-01-1", run_id: "run-01", iteration: 1, prompt_text: "Classify this ticket as technical or billing.", score: 0.74, token_count: 120, latency_ms: 290, diff_tokens: [{type:'equal', text:'Classify the following support ticket...' }, {type:'remove', text:' '}, {type:'add', text:'as technical or billing.'}], created_at: "2026-04-25T10:01:00Z" },
  { id: "var-01-2", run_id: "run-01", iteration: 2, prompt_text: "You are an expert support agent. Classify the ticket into: technical, billing, account, or other.", score: 0.86, token_count: 145, latency_ms: 310, diff_tokens: [{type:'add', text:'You are an expert support agent. '}, {type:'equal', text:'Classify the ticket into: '}, {type:'add', text:'technical, billing, account, or other.'}], created_at: "2026-04-25T10:02:30Z" },
  { id: "var-01-3", run_id: "run-01", iteration: 3, prompt_text: "Analyze the user's message and categorize it strictly as technical, billing, account, or other. Return only the category.", score: 0.91, token_count: 160, latency_ms: 305, diff_tokens: [{type:'add', text:'Analyze the user\'s message and categorize it strictly as '}, {type:'equal', text:'technical, billing, account, or other. '}, {type:'add', text:'Return only the category.'}], created_at: "2026-04-25T10:04:00Z" },
  { id: "var-01-4", run_id: "run-01", iteration: 4, prompt_text: "You are a support classifier. Analyze the input and output exactly one of: technical, billing, account, other.", score: 0.93, token_count: 138, latency_ms: 295, diff_tokens: [{type:'add', text:'You are a support classifier. '}, {type:'equal', text:'Analyze the input and output exactly one of: technical, billing, account, other.'}], created_at: "2026-04-25T10:05:15Z" },
  { id: "var-01-5", run_id: "run-01", iteration: 5, prompt_text: "You are a support classifier. Read the ticket carefully and assign it to exactly one category: technical, billing, account, or other. Do not explain.", score: 0.94, token_count: 142, latency_ms: 320, diff_tokens: [{type:'equal', text:'You are a support classifier. '}, {type:'add', text:'Read the ticket carefully and assign it to exactly one category: technical, billing, account, or other. '}, {type:'add', text:'Do not explain.'}], created_at: "2026-04-25T10:06:30Z" }
];

export const registry = [
  { id: "reg-01", task_name: "Support Ticket Classifier", task_type: "classification", mode: "dataset", prompt_text: "You are a support classifier. Read the ticket carefully and assign it to exactly one category: technical, billing, account, or other. Do not explain.", best_score: 0.94, version: 1, token_count: 142, status: "production", run_id: "run-01", created_at: "2026-04-25T10:08:00Z" },
  { id: "reg-02", task_name: "Contract Summarizer v2", task_type: "summarization", mode: "nodataset", prompt_text: "Condense this legal clause into 2-3 plain English sentences. Highlight obligations and deadlines.", best_score: 0.88, version: 3, token_count: 95, status: "optimizing", run_id: "run-02", created_at: "2026-04-26T11:00:00Z" },
  { id: "reg-03", task_name: "Receipt Parser", task_type: "extraction", mode: "dataset", prompt_text: "Extract structured JSON: {date, amount, vendor, currency} from this receipt text.", best_score: 0.89, version: 1, token_count: 88, status: "production", run_id: "run-03", created_at: "2026-04-26T14:30:00Z" },
  { id: "reg-04", task_name: "Review Authenticity Judge", task_type: "judge", mode: "nodataset", prompt_text: "Evaluate if this review is genuine or fabricated based on linguistic patterns and specificity.", best_score: 0.71, version: 1, token_count: 112, status: "draft", run_id: "run-04", created_at: "2026-04-27T08:05:00Z" }
];

export const activity = [
  { id: 1, type: "run_started", message: "Legal Summarizer started", timestamp: "2026-04-28T07:40:00Z" },
  { id: 2, type: "run_complete", message: "Receipt Data Extractor completed", timestamp: "2026-04-28T06:15:00Z" },
  { id: 3, type: "prompt_saved", message: "Support Ticket Classifier saved to registry", timestamp: "2026-04-27T18:20:00Z" },
  { id: 4, type: "run_failed", message: "Blog Post Generator failed: rate limit", timestamp: "2026-04-27T11:31:00Z" },
  { id: 5, type: "early_stop", message: "Email Triage Assistant hit threshold early", timestamp: "2026-04-27T09:10:00Z" }
];